<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MacBook-Pro-Serhii.local" ignored="0" tests="1" failures="1" timestamp="2018-10-12T23:11:24 EEST" time="0.01" errors="0">
  <testcase name="failTest" time="0.001" classname="FailedTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [java.lang.Object@184f1538] but found [java.lang.Object@39e007b]">
      <![CDATA[java.lang.AssertionError: did not expect to find [java.lang.Object@184f1538] but found [java.lang.Object@39e007b]
at FailedTest.failTest(FailedTest.java:7)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- failTest -->
</testsuite>
